### ISSUE TITLE
Clarification on some input fields

### ISSUE THREAD

**Issue by ibc** [medooze/bwe-stats-viewer#1]
> [Not currently used for stats viewer]

So are those fields required or not?

> Delta time with previous sent rtp packet (0 if lost)

How can a sent packet be "lost"? It may be not received by the remote endpoint, but I'm pretty sure I've sent it so I do know its delta with previous sent.

> Raw Estimated bitrate

😐

> Target bitrate for probing

What is this? If, for instance, I am sending 500kbps and wish to send 700kbps, what does "target bitrate for probing" mean? Is it 200kbps?

> Available bitrate, adjusted bwe estimation reported back to the app (BWE minus RTX allocation based on packet loss)

Why "minus RTX allocation based on packet loss"? RTX packets are not considered different when it comes to compute their delta (at least in transport-cc).

> rtt

Is this the RTT calculated via Sender and Receiver Reports (and XR)?

**Comment by murillo128** [comment]
> > [Not currently used for stats viewer]
> 
> So are those fields required or not?

They are required to be present on the file, but the value is not used, so it can be 0 (not sure if empty)
> 
> > Delta time with previous sent rtp packet (0 if lost)
> 
> How can a sent packet be "lost"? It may be not received by the remote endpoint, but I'm pretty sure I've sent it so I do know its delta with previous sent.

Let's say it other way,  sent delta time of a received packet. That is

`
packet #1 sent at 100 by sender received by receiver at 100 (different clocks)
packet #2 sent at 120 by sender but not received by receiver (i.e. lost)
packet #3 sent at 140 by sender received by receiver at 150 
`
would have deltas
`
packet #1 delta sent:0 delta recv:0 delta:0 (as it is the first packet)
packet #2 delta sent:0 delta recv:0 delta:0 (as it is lost packet)
packet #3 delta sent: 40 delta recv: 50 delta: 10 (packet#3 - packet#1)
`


> 
> > Raw Estimated bitrate
> 
> 😐

This is the estimation provided by the algorithm without further adjustments
> 
> > Target bitrate for probing
> 
> What is this? If, for instance, I am sending 500kbps and wish to send 700kbps, what does "target bitrate for probing" mean? Is it 200kbps?

In my algorithm, I have an instant bitrate for probing and I only update the estimation 1 per second, so if probing bitrate > sent media, the rest is filled with probing. You can just set it to 0 if it doesn't apply.

> 
> > Available bitrate, adjusted bwe estimation reported back to the app (BWE minus RTX allocation based on packet loss)
> 
> Why "minus RTX allocation based on packet loss"? RTX packets are not considered different when it comes to compute their delta (at least in transport-cc).

At least in my case, I allocate some bitrate for future RTX based on current loss, so the available bitrate  would be aprox raw estimate * (100- packet loss %). 

> 
> > rtt
> 
> Is this the RTT calculated via Sender and Receiver Reports (and XR)?

yes

**Comment by ibc** [comment]
Thanks, let me please come back to this in next days.

**Comment by murillo128** [comment]
ping me if you need anything

**Comment by ibc** [comment]
I have to put this on hold for a while. You know. Just 24 hours a day...
