### ISSUE TITLE
Show loss rate graph

### ISSUE THREAD

**Issue by JonathanLennox** [medooze/bwe-stats-viewer#2]
I think a good model for what a loss rate graph should look like is Xiaoqing Zhu's NADA graphs in the NADA presentations slides from RMCAT - https://datatracker.ietf.org/meeting/106/materials/slides-106-rmcat-nada-update, e.g. page 6.

**Comment by murillo128** [comment]
In latest version I have added a new serie in the bottom graph with the % of packet losses over a 250ms window. 

I think that the data is the same, just the visualization is a bit different (connected line serie instead of dotted one).  Have you tried it?

**Comment by JonathanLennox** [comment]
Ah, I see!  Yeah, that seems decent.

I might put it on a separate graph than the time-related stats? But yes, it's reasonable.

**Comment by murillo128** [comment]
I need to improve the line series visualization, because currently it is very messy and difficult to differentiate lines. But i think is better to have only two graphs then add a new one that would make it difficult to view all of them simultaneously.
